[package]
name = "stackyzdev/signal"
description = "Signal Class"
version = "1.0.0"
license = "MIT"
authors = ["Kauã Rosa Borges"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["node_modules", "package.json"]